// SPDX-FileCopyrightText: 2019 ZelteHonor <gabrieldionbouchard@gmail.com>
// SPDX-FileCopyrightText: 2020 DTanxxx <55208219+DTanxxx@users.noreply.github.com>
// SPDX-FileCopyrightText: 2020 Vince <39844191+Visne@users.noreply.github.com>
// SPDX-FileCopyrightText: 2020 Víctor Aguilera Puerto <6766154+Zumorica@users.noreply.github.com>
// SPDX-FileCopyrightText: 2021 Acruid <shatter66@gmail.com>
// SPDX-FileCopyrightText: 2021 DrSmugleaf <DrSmugleaf@users.noreply.github.com>
// SPDX-FileCopyrightText: 2021 Pieter-Jan Briers <pieterjan.briers+git@gmail.com>
// SPDX-FileCopyrightText: 2021 Swept <sweptwastaken@protonmail.com>
// SPDX-FileCopyrightText: 2022 20kdc <asdd2808@gmail.com>
// SPDX-FileCopyrightText: 2022 Just-a-Unity-Dev <just-a-unity-dev@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 Paul Ritter <ritter.paul1@googlemail.com>
// SPDX-FileCopyrightText: 2022 eclips_e <67359748+Just-a-Unity-Dev@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 mirrorcult <lunarautomaton6@gmail.com>
// SPDX-FileCopyrightText: 2022 wrexbe <81056464+wrexbe@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
//
// SPDX-License-Identifier: MIT


using Robust.Client.UserInterface.CustomControls;
using Content.Client.Info;
using Content.Client.UserInterface.Systems.EscapeMenu;
using Content.Client.UserInterface.Systems.Guidebook;
using Content.Shared._CorvaxGoob.CCCVars;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Player;
using Robust.Client.Console;
using Robust.Shared.Configuration;
using Content.Client.UserInterface.Systems.Ghost.Controls;
using Content.Client.Stylesheets;
using Robust.Client.UserInterface.Controls;
using Content.Client.UserInterface.Systems.Ghost;
using Content.Shared.Ghost;
using Content.Client.Ghost;
using Content.Client.UserInterface.Systems.Ghost;

namespace Content.Client.Options.UI
{

    [GenerateTypedNameReferences]
    public sealed partial class EscapeMenu : DefaultWindow
    {
        [Dependency] private readonly IUriOpener _uriOpener = default!;
        [Dependency] private readonly IClientConsoleHost _consoleHost = default!;
        [Dependency] private readonly IPlayerManager _playerManager = default!;
        [Dependency] private readonly IConfigurationManager _cfg = default!;
        public EscapeMenu()
        {
            RobustXamlLoader.Load(this);
            Boosty.OnPressed += _ => _uriOpener.OpenUri(new Uri("https://boosty.to/freakystation"));
            CoinShop.OnPressed += _ => _consoleHost.ExecuteCommand("balanceui");
            Discord.OnPressed += _ => _uriOpener.OpenUri(new Uri("https://discord.gg/NMqvMnqNA6"));
        }
    }
}
